services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@Typo//map
      MYSQL_DATABASE: typomapdb
      MYSQL_USER: typo
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: P@Typo//map
    ports:
      - "5481:80"
    networks:
      - my_network

  apache_php:
    build:
      context: frontapp
      dockerfile: Dockerfile
    container_name: apache_php
    restart: always
    ports:
      - "5480:80"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
