services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: typomapdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "5481:80"
    networks:
      - my_network
    env_file:
      - .env

  back:
    build:
      context: backapp
      dockerfile: Dockerfile
    container_name: backapp
    restart: always
    ports:
      - "5482:80"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: typomapdb
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_network
    volumes:
      - ./backapp:/var/www/html
    env_file:
      - .env

  front:
    build:
      context: frontapp
      dockerfile: Dockerfile
    container_name: frontapp
    restart: always
    ports:
      - "5480:80"
    networks:
      - my_network
    volumes:
      - ./www:/var/www/html

networks:
  my_network:
    driver: bridge
