services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: typomapdb
      MYSQL_USER: ${MSQL_USER}
      MYSQL_PASSWORD: ${MSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "5481:80"
    networks:
      - my_network

  front:
    build:
      context: frontapp
      dockerfile: Dockerfile
    container_name: frontapp
    restart: always
    ports:
      - "5480:80"
    networks:
      - my_network

  back:
    build:
      context: backapp
      dockerfile: Dockerfile
    container_name: backapp
    restart: always
    ports:
      - "5482:80"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
